=== jenishbasnet/project5/catalog_19031667.dtd
<!ELEMENT MusicStore (StoreName,Address,TelephoneNumber,Website,Logo,Songs)>
        <!ELEMENT StoreName (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT TelephoneNumber (#PCDATA)>
        <!ELEMENT Logo (#PCDATA)>
        <!ELEMENT Website (#PCDATA)>
        <!ELEMENT Songs (Song+)>
        <!ELEMENT Song (SongName,Genre,Directors,Producers,Writters,Singers,ReleaseYear,SongLength,Album?,BillboarddRank?,Award?,Label?,Price)> 
        <!ELEMENT SongName (#PCDATA)>
        <!ELEMENT Genre (#PCDATA)>
        <!ELEMENT Directors (DirectorName?,CoDirectorName?,AssistantDirectorName?)>
        <!ELEMENT DirectorName (#PCDATA)>
        <!ELEMENT CoDirectorName (#PCDATA)>
        <!ELEMENT AssistantDirectorName (#PCDATA)>
        <!ELEMENT Producers (ProducerName,CoProducerName?,ProductionCompany?)>
        <!ELEMENT ProducerName (#PCDATA)>
        <!ELEMENT CoProducerName (#PCDATA)>
        <!ELEMENT ProductionCompany (#PCDATA)>
        <!ELEMENT Writters (WritterName,CoWritterName?)>
        <!ELEMENT WritterName (#PCDATA)>
        <!ELEMENT CoWritterName (#PCDATA)>
        <!ELEMENT Singers (LeadSinger+,FeaturingSinger?,Vocalist?)>
        <!ELEMENT LeadSinger (#PCDATA)>
        <!ELEMENT FeaturingSinger (#PCDATA)>
        <!ELEMENT Vocalist (#PCDATA)>
        <!ELEMENT ReleaseYear (#PCDATA)>
        <!ELEMENT SongLength (#PCDATA)>
        <!ELEMENT Album (#PCDATA)>
        <!ELEMENT BillboarddRank (#PCDATA)>
        <!ELEMENT Award (#PCDATA)>
        <!ELEMENT Label (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>

        <!ATTLIST Song song_id ID #REQUIRED>
        <!ATTLIST DirectorName title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST CoDirectorName title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST AssistantDirectorName title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST ProducerName title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST CoProducerName title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST WritterName title (Mr. | Mrs.) #REQUIRED>
        
        <!ATTLIST LeadSinger title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST FeaturingSinger title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST Vocalist title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST CoWritterName title (Mr. | Mrs.) #REQUIRED>
        <!ATTLIST Album type (Single | Studio | Live) #REQUIRED>
        <!ATTLIST Award won (GrammyAward | BillboardMusicAward) #IMPLIED>
        <!ATTLIST BillboarddRank scale CDATA #IMPLIED>

=== jenishbasnet/project5/catalog_19031667.xml
<?xml version="1.0"?>
<!-- XML Song Record for music store-->
<!-- 
   Author: Jenish Basnet  
   London Met ID:19031667
-->
<!DOCTYPE MusicStore SYSTEM "catalog_19031667.dtd">

<?xml-stylesheet type="text/css" href="catalog_19031667.css"?>   
<MusicStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19031667.xsd">
    <StoreName>Music Hub</StoreName>
    <Address>Kathmandu [Ring Road]</Address>
    <TelephoneNumber>9812335566</TelephoneNumber>
    <Website>www.musichub.com</Website>
    <Logo></Logo>
    <Songs>
        <Song song_id="S01">
            <SongName>Blinding Light</SongName>
            <Genre>Pop</Genre>
            <Directors>
                <DirectorName title="Mr.">Anton Tammi</DirectorName>
                <CoDirectorName title="Mr.">Oliver Millar</CoDirectorName>
                <AssistantDirectorName title="Mr.">Aleksi Tammi</AssistantDirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mrs.">Sarah Park</ProducerName>
                <CoProducerName title="Mrs.">Saskia Whinney</CoProducerName>
                <ProductionCompany>Somesuch</ProductionCompany>
            </Producers>
            <Writters>
                <WritterName title="Mr.">Abel Makkonen Tesfaye</WritterName>
                <CoWritterName title="Mr.">Balshe Ahmed</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mr.">Abel Makkonen Tesfaye</LeadSinger>
                <FeaturingSinger title="Mr.">Teddy Swims</FeaturingSinger>
                <Vocalist title="Mr.">Nicole Milk</Vocalist>
            </Singers>
            <ReleaseYear>2020</ReleaseYear>
            <SongLength>3:22</SongLength>
            <Album type="Studio">After Hours</Album>
            <BillboarddRank scale="15"/>
            <Award won="BillboardMusicAward"/>
            <Label>Republic</Label>
            <Price>450</Price>
        </Song>
        <Song song_id="S02">
            <SongName>Monster</SongName>
            <Genre>Hip hop</Genre>
            <Directors>
                <DirectorName title="Mr.">Rich Lee</DirectorName>
                <CoDirectorName title="Mr.">John D'Aquino</CoDirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mr.">Bryan Fryzel</ProducerName>
                <CoProducerName title="Mr.">Aaron Kleinstub</CoProducerName>
            </Producers>
            <Writters>
                <WritterName title="Mr.">Marshall Bruce Mathers</WritterName>
                <CoWritterName title="Mrs.">Robyn Rihanna Fenty</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mr.">Marshall Bruce Mathers</LeadSinger>
                <FeaturingSinger title="Mrs.">Robyn Rihanna Fenty</FeaturingSinger>
            </Singers>
            <ReleaseYear>2013</ReleaseYear>
            <SongLength>5:18</SongLength>
            <Album type="Studio">The Marshall Mathers LP 2</Album>
            <BillboarddRank scale="14"/>
            <Award won="GrammyAward"/>
            <Label>Interscope</Label>
            <Price>650</Price>
        </Song>
        <Song song_id="S03">
            <SongName>Comethru</SongName>
            <Genre>Pop</Genre>
            <Directors>
                <DirectorName title="Mr.">Ben Schmidt</DirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mr.">Ben Schmidt</ProducerName>
            </Producers>
            <Writters>
                <WritterName title="Mr.">Jermy Jucker</WritterName>
                <CoWritterName title="Mrs.">Summer Marjani Walker</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mr.">Jermy Jucker</LeadSinger>
            </Singers>
            <ReleaseYear>2020</ReleaseYear>
            <SongLength>2:59</SongLength>
            <Price>650</Price>
        </Song>
        <Song song_id="S04">
            <SongName>I Don't Wanna Live Forever</SongName>
            <Genre>Pop</Genre>
            <Directors>
                <DirectorName title="Mr.">Natalie Diane Grant</DirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mr.">Saul Germaine</ProducerName>
                <CoProducerName title="Mr.">Jack Antonoff</CoProducerName>
                <ProductionCompany>Fifty Shades Vevo</ProductionCompany>
            </Producers>
            <Writters>
                <WritterName title="Mrs.">Taylor Alison Swift</WritterName>
                <CoWritterName title="Mr.">Sam Dew</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mrs.">Taylor Alison Swift</LeadSinger>
                <FeaturingSinger title="Mr.">Zain Javadd Malik</FeaturingSinger>
            </Singers>
            <ReleaseYear>2016</ReleaseYear>
            <SongLength>4:05</SongLength>
            <Label>Republic Records</Label>
            <Price>600</Price>
        </Song>
        <Song song_id="S05">
            <SongName>Hold My Hand</SongName>
            <Genre>Pop</Genre>
            <Directors>
                <DirectorName title="Mr.">Michael Joseph Jackson</DirectorName>
                <CoDirectorName title="Mr.">Giorgio H. Tuinfort</CoDirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mr.">Michael Joseph Jackson</ProducerName>
                <CoProducerName title="Mr.">Aliaume Damala Badara Akon Thiam</CoProducerName>
            </Producers>
            <Writters>
                <WritterName title="Mr.">Aliaune Thiam</WritterName>
                <CoWritterName title="Mr.">Claude Kelly</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mr.">Michael Joseph Jackson</LeadSinger>
                <FeaturingSinger title="Mr.">Aliaume Damala Badara Akon Thiam</FeaturingSinger>
            </Singers>
            <ReleaseYear>2010</ReleaseYear>
            <SongLength>3:43</SongLength>
            <BillboarddRank scale="39"/>
            <Label>Epic</Label>
            <Price>630</Price>
        </Song>
        <Song song_id="S06">
            <SongName>Time to Pretend</SongName>
            <Genre>Rock</Genre>
            <Directors>
                <DirectorName title="Mr.">Ray Tintori</DirectorName>
                <CoDirectorName title="Mr.">Karyn Kusama</CoDirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mr.">Dave Fridmann</ProducerName>
            </Producers>
            <Writters>
                <WritterName title="Mr.">Ben Goldwasser</WritterName>
                <CoWritterName title="Mr.">Andrew VanWyngarden</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mr.">Andrew VanWyngarden</LeadSinger>
                <FeaturingSinger title="Mr.">Hank Sullivant</FeaturingSinger>
                <Vocalist title="Mr.">Ben Goldwasser</Vocalist>
            </Singers>
            <ReleaseYear>2008</ReleaseYear>
            <SongLength>4:19</SongLength>
            <Label>Columbia Records</Label>
            <Price>300</Price>
        </Song>
        <Song song_id="S07">
            <SongName>No Time to Die</SongName>
            <Genre>Pop</Genre>
            <Directors>
                <DirectorName title="Mr.">Daniel Kleinman</DirectorName>
                <CoDirectorName title="Mr.">Rachel McRady</CoDirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mr.">O'Connell</ProducerName>
                <CoProducerName title="Mr.">Stephen Lipson</CoProducerName>
            </Producers>
            <Writters>
                <WritterName title="Mrs.">Billie Eilish</WritterName>
                <CoWritterName title="Mr.">Finneas Baird O'Connell</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mrs.">Billie Eilish</LeadSinger>
            </Singers>
            <ReleaseYear>2019</ReleaseYear>
            <SongLength>4:02</SongLength>
            <Album type="Single">No Time to Die</Album>
            <BillboarddRank scale="11"/>
            <Award won="BillboardMusicAward"/>
            <Label>Interscope Records</Label>
            <Price>650</Price>
        </Song>
        <Song song_id="S08">
            <SongName>(I've Had) The Time Of My Life</SongName>
            <Genre>Soft Rock</Genre>
            <Directors>
                <DirectorName title="Mr.">Bill Medley</DirectorName>
                <CoDirectorName title="Mr.">Franke Previte</CoDirectorName>
            </Directors>
            <Producers>
                <ProducerName title="Mr.">Michael Jeffrey Lloyd</ProducerName>
                <ProductionCompany>RCA Records</ProductionCompany>
            </Producers>
            <Writters>
                <WritterName title="Mr.">John DeNicola</WritterName>
                <CoWritterName title="Mr.">Donald Markowitz</CoWritterName>
            </Writters>
            <Singers>
                <LeadSinger title="Mr.">Bill Medley</LeadSinger>
                <FeaturingSinger title="Mrs.">Jennifer Warnes</FeaturingSinger>
            </Singers>
            <ReleaseYear>1987</ReleaseYear>
            <SongLength>4:42</SongLength>
            <Album type="Live">Dirty Dancing Soundtrack</Album>
            <BillboarddRank scale="65"/>
            <Award won="GrammyAward"/>
            <Label>RCA Records</Label>
            <Price>550</Price>
        </Song>
        <Song song_id="S09">
            <SongName>God Only Knows</SongName>
            <Genre>Pop</Genre>
            <Directors>
                <DirectorName title="Mr.">Kirk Franklin</DirectorName>
                <CoDirectorName title="Mrs.">Nadja Salerno-Sonnenberg</CoDirectorName>
            </Directors>
            <Producers>
